// Automatically generated by astro-icon
// e17ddae6f732f8f13b6f59ed35cc8f61f26dcd7333f75143a9817aa04c13ab6d

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ion:earth"
		| "ion:logo-github"
		| "ion:logo-twitter"
		| "ion:logo-linkedin"
		| "ion:logo-instagram"
		| "ion:logo-youtube"
		| "lucide:briefcase-business"
		| "lucide:command"
		| "lucide:house"
		| "lucide:library"
		| "lucide:mail-plus"
		| "lucide:monitor-cog"
		| "lucide:notebook-pen"
		| "lucide:palette"
		| "lucide:pen-line"
		| "lucide:rss"
		| "lucide:square-user"
		| "lucide:home"
		| "ri:quill-pen-fill"
		| "simple-icons:astro"
		| "tabler:alert-circle";
}