#:schema ../../.astro/collections/climes.schema.json
["200"]
description = "thunderstorm with light rain"
icon        = "11d"
main        = "Thunderstorm"

["201"]
description = "thunderstorm with rain"
icon        = "11d"
main        = "Thunderstorm"

["202"]
description = "thunderstorm with heavy rain"
icon        = "11d"
main        = "Thunderstorm"

["210"]
description = "light thunderstorm"
icon        = "11d"
main        = "Thunderstorm"

["211"]
description = "thunderstorm"
icon        = "11d"
main        = "Thunderstorm"

["212"]
description = "heavy thunderstorm"
icon        = "11d"
main        = "Thunderstorm"

["221"]
description = "ragged thunderstorm"
icon        = "11d"
main        = "Thunderstorm"

["230"]
description = "thunderstorm with light drizzle"
icon        = "11d"
main        = "Thunderstorm"

["231"]
description = "thunderstorm with drizzle"
icon        = "11d"
main        = "Thunderstorm"

["232"]
description = "thunderstorm with heavy drizzle"
icon        = "11d"
main        = "Thunderstorm"

["300"]
description = "light intensity drizzle"
icon        = "09d"
main        = "Drizzle"

["301"]
description = "drizzle"
icon        = "09d"
main        = "Drizzle"

["302"]
description = "heavy intensity drizzle"
icon        = "09d"
main        = "Drizzle"

["310"]
description = "light intensity drizzle rain"
icon        = "09d"
main        = "Drizzle"

["311"]
description = "drizzle rain"
icon        = "09d"
main        = "Drizzle"

["312"]
description = "heavy intensity drizzle rain"
icon        = "09d"
main        = "Drizzle"

["313"]
description = "shower rain and drizzle"
icon        = "09d"
main        = "Drizzle"

["314"]
description = "heavy shower rain and drizzle"
icon        = "09d"
main        = "Drizzle"

["321"]
description = "shower drizzle"
icon        = "09d"
main        = "Drizzle"

["500"]
description = "light rain"
icon        = "10d"
main        = "Rain"

["501"]
description = "moderate rain"
icon        = "10d"
main        = "Rain"

["502"]
description = "heavy intensity rain"
icon        = "10d"
main        = "Rain"

["503"]
description = "very heavy rain"
icon        = "10d"
main        = "Rain"

["504"]
description = "extreme rain"
icon        = "10d"
main        = "Rain"

["511"]
description = "freezing rain"
icon        = "13d"
main        = "Rain"

["520"]
description = "light intensity shower rain"
icon        = "09d"
main        = "Rain"

["521"]
description = "shower rain"
icon        = "09d"
main        = "Rain"

["522"]
description = "heavy intensity shower rain"
icon        = "09d"
main        = "Rain"

["531"]
description = "ragged shower rain"
icon        = "09d"
main        = "Rain"

["600"]
description = "light snow"
icon        = "13d"
main        = "Snow"

["601"]
description = "snow"
icon        = "13d"
main        = "Snow"

["602"]
description = "heavy snow"
icon        = "13d"
main        = "Snow"

["611"]
description = "sleet"
icon        = "13d"
main        = "Snow"

["612"]
description = "light shower sleet"
icon        = "13d"
main        = "Snow"

["613"]
description = "shower sleet"
icon        = "13d"
main        = "Snow"

["615"]
description = "light rain and snow"
icon        = "13d"
main        = "Snow"

["616"]
description = "rain and snow"
icon        = "13d"
main        = "Snow"

["620"]
description = "light shower snow"
icon        = "13d"
main        = "Snow"

["621"]
description = "shower snow"
icon        = "13d"
main        = "Snow"

["622"]
description = "heavy shower snow"
icon        = "13d"
main        = "Snow"

["701"]
description = "mist"
icon        = "50d"
main        = "Mist"

["711"]
description = "smoke"
icon        = "50d"
main        = "Smoke"

["721"]
description = "haze"
icon        = "50d"
main        = "Haze"

["731"]
description = "sand/dust whirls"
icon        = "50d"
main        = "Dust"

["741"]
description = "fog"
icon        = "50d"
main        = "Fog"

["751"]
description = "sand"
icon        = "50d"
main        = "Sand"

["761"]
description = "dust"
icon        = "50d"
main        = "Dust"

["762"]
description = "volcanic ash"
icon        = "50d"
main        = "Ash"

["771"]
description = "squalls"
icon        = "50d"
main        = "Squall"

["781"]
description = "tornado"
icon        = "50d"
main        = "Tornado"

["800"]
description = "clear sky"
icon        = "01d"
main        = "Clear"

["801"]
description = "few clouds"
icon        = "02d"
main        = "Clouds"

["802"]
description = "scattered clouds"
icon        = "03d"
main        = "Clouds"

["803"]
description = "broken clouds"
icon        = "04d"
main        = "Clouds"

["804"]
description = "overcast clouds"
icon        = "04d"
main        = "Clouds"
