#:schema ../../.astro/collections/routes.schema.json
[home]
href  = "/"
icon  = "lucide:house"
order = 0
text  = "home"

[about]
href  = "/about"
icon  = "lucide:user-round-pen"
order = 2
text  = "about me"


[projects]
href  = "/projects"
icon  = "lucide:flask-conical"
order = 3
text  = "projects"

[posts]
href  = "/posts"
icon  = "lucide:file-text"
order = 4
text  = "posts"


[journal]
href  = "/journal"
icon  = "lucide:files"
order = 5
text  = "journal"

[wiki]
href  = "/wiki"
icon  = "lucide:library"
order = 6
text  = "wiki"

[contact]
href  = "/hello"
icon  = "lucide:mail-plus"
order = 7
text  = "contact me"
