#:schema https://www.schemastore.org/taplo.json
exclude = ["node_modules/**/*.toml"]

# https://taplo.tamasfe.dev/configuration/formatter-options.html
[formatting]
align_entries       = true
array_auto_collapse = false
array_auto_expand   = true
column_width        = 96
inline_table_expand = false
reorder_keys        = true
