nodeLinker: node-modules

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@astrojs/*"
  - "@bruits/*"
  - "@iconify-json/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - "@tailwindcss/*"
  - "@typescript/*"
  - "@types/node"
  - astro
  - satteri
  - tailwindcss
  - oxlint
  - oxlint-tsgolint
  - oxfmt
  - prettier
  - typescript
