nodeLinker: node-modules

npmMinimalAgeGate: "3d"

npmPreapprovedPackages:
  - "@astrojs/*"
  - "@bruits/*"
  - "@iconify-json/*"
  - "@oxfmt/*"
  - "@oxlint/*"
  - "@oxlint-tsgolint/*"
  - "@tailwindcss/*"
  - "@typescript/native-preview"
  - "@typescript/native-preview-*"
  - "@types/node"
  - "astro"
  - "satteri"
  - "tailwindcss"
  - "oxlint"
  - "oxlint-tsgolint"
  - "oxfmt"
  - "prettier"
