## (optional) Settings for Netlify Dev
## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
#[dev]
#  command = "pnpm start" # Command to start your dev server
#  port = 3000 # Port that the dev server will be listening on
#  publish = "dist" # Folder with the static content for _redirect file

## more info on configuring this file: https://ntl.fyi/file-based-build-config

[build]
    command = "corepack enable && pnpm run build"
    publish = "dist"
    # edge_functions = "netlify/edge-functions"
    # functions      = "netlify/functions"
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

    [build.environment]
        COREPACK_ENABLE_STRICT = "0"

[context.main]
    command = "corepack enable && DEPLOY_CHANNEL=stable pnpm run build"

[context.beta]
    command = "corepack enable && DEPLOY_CHANNEL=beta pnpm run build"

[context.nightly]
    command = "corepack enable && DEPLOY_CHANNEL=nightly pnpm run build"

# Branch deploy settings
[context.branch-deploy]
    command = "corepack enable && DEPLOY_CHANNEL=branch pnpm run build"

# Deploy previews for PRs
[context.deploy-preview]
    command = "corepack enable && DEPLOY_CHANNEL=preview pnpm run build"

[[redirects]]
    force = true                      # ensure to always redirect
    from = "/api/*"                   # simplify all calls to serverless functions
    status = 200                      # ok code
    to = "/.netlify/functions/:splat" # all function calls will go to this path

[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
        Content-Type = "application/manifest+json"

[[headers]]
    for = "/sw.js"
    [headers.values]
        Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
    for = "/_astro/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
    for = "/*"
    [headers.values]
        CDN-Cache-Control = "public, durable, s-maxage=18000, stale-while-revalidate=604800, stale-if-error=604800, immutable"
        Cache-Control = "public, max-age=3600, must-revalidate"
        Netlify-CDN-Cache-Control = "public, durable, s-maxage=18000, stale-while-revalidate=604800, stale-if-error=604800, immutable"
        Permissions-Policy = "geolocation=(), camera=(), microphone=()"
        Referrer-Policy = "strict-origin-when-cross-origin"
        Strict-Transport-Security = "max-age=31536000"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
