packages:
  - apps/*
  - pkgs/*
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

catalog:
  "@dotenvx/dotenvx": ^1.51.1
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^25.3.5
  oxfmt: ^0.41.0
  oxlint: ^1.57.0
  oxlint-tsgolint: ^0.17.4
  prettier: ^3.8.1
  tsx: 4.21.0
  typescript: ^6.0.2

catalogMode: manual

overrides:
  vite: "^7"
