packages:
  - apps/*
  - pkgs/*

catalog:
  "@dotenvx/dotenvx": ^1.51.1
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^25.3.5
  oxfmt: ^0.41.0
  oxlint: ^1.56.0
  oxlint-tsgolint: ^0.17.2
  prettier: ^3.8.1
  tsx: 4.21.0
  typescript: ^6.0.2
  vite: ^7.3.1

catalogMode: manual

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: true
