
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const EventType = {
  PAGE_VIEW: 'PAGE_VIEW',
  CLICK: 'CLICK',
  SCROLL: 'SCROLL',
  KEYDOWN: 'KEYDOWN',
  PAGE_EXIT: 'PAGE_EXIT'
} as const

export type EventType = (typeof EventType)[keyof typeof EventType]


export const ReactionType = {
  LIKE: 'LIKE',
  LOVE: 'LOVE',
  CLAP: 'CLAP',
  INSIGHTFUL: 'INSIGHTFUL'
} as const

export type ReactionType = (typeof ReactionType)[keyof typeof ReactionType]
