// oxlint-disable no-ternary
// oxlint-disable no-unsafe-type-assertion
// SPDX-License-Identifier: Apache-2.0
export const serialize = <T>(data: T, options?: StructuredSerializeOptions) =>
  structuredClone(data, options);

type Key = string | number | symbol;
export function omit<T extends Record<Key, unknown>, K extends keyof T>(obj: T, key: K): Omit<T, K>;
export function omit<T extends Record<Key, unknown>, K extends keyof T>(
  obj: T,
  keys: readonly K[],
): Omit<T, K>;
export function omit<T extends Record<Key, unknown>, K extends keyof T>(
  obj: T,
  keyOrKeys: K | readonly K[],
): Omit<T, K> {
  const keys = (Array.isArray(keyOrKeys) ? keyOrKeys : [keyOrKeys]) as readonly K[];
  const keySet = new Set(keys);
  const result: T = {} as T;

  // oxlint-disable-next-line no-unsafe-type-assertion
  for (const key of Reflect.ownKeys(obj) as K[]) {
    if (!keySet.has(key)) result[key] = obj[key];
  }

  return result as Omit<T, K>;
}

/**
 * Remembers and retrieves a value by a given name, or the value generated by `getValue` if the name doesn't exist.
 * The return type is inferred from the return type of `getValue`.
 *
 * @template T
 * @param {string} name - The name under which to remember the value.
 * @param {() => T} getValue - The function that generates the value to remember.
 * @returns {NonNullable<T>} - The remembered value.
 */
export const remember = <T>(name: string, getValue: () => T) => {
  const g = globalThis;
  g.__singletons__ ??= new Map();
  if (!g.__singletons__.has(name)) g.__singletons__.set(name, getValue());
  return g.__singletons__.get(name) as NonNullable<T>;
};

/**
 * Forgets a remembered value by a given name. Does not throw if the name doesn't exist.
 *
 * @param {string} name - The name under which the value was remembered.
 * @return {boolean} - A remembered value existed and has been forgotten.
 */
export const forget = (name: string) => {
  const g = globalThis;
  g.__singletons__ ??= new Map();
  return g.__singletons__.delete(name);
};
