#:schema ../../.astro/collections/socials.schema.json
[discord]
color = "text-indigo-600"
href  = "https://discord.gg/vW7dnUVGP9"
icon  = "ion:logo-discord"
text  = "Join our Discord server"
order = 0

[twitter]
color = "text-blue-500"
href  = "https://x.com/intent/follow?screen_name=iamprincemuel"
icon  = "ion:logo-twitter"
text  = "Follow Me on Twitter/X"
order = 1

[instagram]
color = "text-pink-500"
href  = "https://instagram.gg/vW7dnUVGP9"
icon  = "ion:logo-instagram"
text  = "Follow me on Instagram"
order = 2

[youtube]
color = "text-red-600"
href  = "https://youtube.com/@iamprincemuel"
icon  = "ion:logo-youtube"
text  = "Subscribe to my YouTube Channel"
order = 3

[linkedin]
color = "text-blue-700"
href  = "https://www.linkedin.com/in/princemuel"
icon  = "ion:logo-linkedin"
text  = "Connect with me on LinkedIn"
order = 4

[website]
color = "text-green-700"
href  = "https://princemuel.netlify.app/about"
icon  = "ion:earth"
text  = "Connect with me on LinkedIn"
order = 5

[github]
color = "text-slate-900 dark:text-slate-100"
href  = "https://github.com/princemuel"
icon  = "ion:logo-github"
text  = "Check out my projects on GitHub"
order = 6

[email]
color = "text-red-500"
href  = "mail:to:vansomecsam@gmail.com"
icon  = "lucide:mail-plus"
text  = "Send me a message"
order = 7

[rss]
color = "text-slate-500"
href  = "/rss.xml"
icon  = "lucide:rss"
text  = "Subscribe to my rss feed"
order = 8

[mastodon]
color = "text-indigo-600"
href  = "https://mastodon.social/@princemuel"
icon  = "ion:logo-mastodon"
text  = "Follow me on Mastodon"
order = 9

[keyoxide]
color = "text-indigo-400"
href  = "https://keyoxide.org/u/princemuel"
icon  = "keyoxide"
text  = "Verify my identity on Keyoxide"
order = 10
