// oxlint-disable typescript/unified-signatures
export const serialize = <T>(data: T, options?: StructuredSerializeOptions) =>
  structuredClone(data, options);

type Key = string | number | symbol;
export function omit<T extends Record<Key, unknown>, K extends keyof T>(
  obj: T,
  key: K,
): Omit<T, K>;
export function omit<T extends Record<Key, unknown>, K extends keyof T>(
  obj: T,
  keys: readonly K[],
): Omit<T, K>;
export function omit<T extends Record<Key, unknown>, K extends keyof T>(
  obj: T,
  keyOrKeys: K | readonly K[],
): Omit<T, K> {
  const keys = new Set((Array.isArray(keyOrKeys) ? keyOrKeys : [keyOrKeys]) as K[]);
  const result: T = {} as T;

  for (const key of Reflect.ownKeys(obj) as K[]) if (!keys.has(key)) result[key] = obj[key];
  return result;
}

/**
 * Remembers and retrieves a value by a given key, or the value generated by `getValue` if the
 * key doesn't exist. The return type is inferred from the return type of `getValue`.
 *
 * @template T
 * @param {string} key - The key under which to remember the value.
 * @param {() => T} getValue - The function that generates the value to remember.
 * @returns {NonNullable<T>} - The remembered value.
 */
export const remember = <T>(key: string, getValue: () => NonNullable<T>): NonNullable<T> => {
  const g = globalThis;
  return (g.__singletons__ ??= new Map()).getOrInsertComputed(key, () =>
    getValue(),
  ) as NonNullable<T>;
};

/**
 * Forgets a remembered value by a given key. Does not throw if the key doesn't exist.
 *
 * @param {string} key - The key under which the value was remembered.
 * @returns {boolean} - A remembered value existed and has been forgotten.
 */
export const forget = (key: string): boolean => {
  const g = globalThis;
  return (g.__singletons__ ??= new Map()).delete(key);
};
